import { ComponentSchema, SchemaProps } from '../types';

export const flagDisplaySpriteSchema = (props: SchemaProps): ComponentSchema => ({
  type: 'flag-display-sprite',
  label: 'Flag Display (Sprite)',
  icon: 'Flag',
  allowChildren: false,
  bindable: true,
  fields: {
    name:   { label: 'Name', type: 'text' },
    x:      { label: 'X', type: 'slider', min: -1000, max: 5000, section: 'Layout' },
    y:      { label: 'Y', type: 'slider', min: -1000, max: 5000, section: 'Layout' },
    width:  { label: 'Width', type: 'slider', min: 4, max: 5000, section: 'Layout' },
    height: { label: 'Height', type: 'slider', min: 4, max: 5000, section: 'Layout' },
    fileOff:         { label: 'Sprite — Off', type: 'select', options: props.spriteOptions, section: 'Flag Images' },
    fileGreen:       { label: 'Sprite — Green', type: 'select', options: props.spriteOptions, section: 'Flag Images' },
    fileYellow:      { label: 'Sprite — Yellow', type: 'select', options: props.spriteOptions, section: 'Flag Images' },
    fileRed:         { label: 'Sprite — Red', type: 'select', options: props.spriteOptions, section: 'Flag Images' },
    fileBlue:        { label: 'Sprite — Blue', type: 'select', options: props.spriteOptions, section: 'Flag Images' },
    fileWhite:       { label: 'Sprite — White', type: 'select', options: props.spriteOptions, section: 'Flag Images' },
    fileChequered:   { label: 'Sprite — Chequered', type: 'select', options: props.spriteOptions, section: 'Flag Images' },
    fileBlack:       { label: 'Sprite — Black', type: 'select', options: props.spriteOptions, section: 'Flag Images' },
    fileBlackWhite:  { label: 'Sprite — Black & White', type: 'select', options: props.spriteOptions, section: 'Flag Images' },
    fileBlackOrange: { label: 'Sprite — Black & Orange', type: 'select', options: props.spriteOptions, section: 'Flag Images' },
    fileOrange:      { label: 'Sprite — Orange', type: 'select', options: props.spriteOptions, section: 'Flag Images' },
    fileInPit:       { label: 'Sprite — In Pit', type: 'select', options: props.spriteOptions, section: 'Flag Images' },
    showGear:     { label: 'Show gear (on green)', type: 'checkbox', section: 'Gear' },
    gearFontSize: { label: 'Gear font size', type: 'slider', min: 4, max: 400, section: 'Gear' },
    gearColor:    { label: 'Gear colour', type: 'text', section: 'Gear' },
    gearOffsetX:  { label: 'Gear offset X', type: 'slider', min: -500, max: 500, section: 'Gear' },
    gearOffsetY:  { label: 'Gear offset Y', type: 'slider', min: -500, max: 500, section: 'Gear' },
  },
});
